version: 0.2

phases:
  install:
    commands:
      - echo "Installing awscli"
      - apt-get update -y
      - apt-get install -y awscli
  pre_build:
    commands:
      - echo "Nothing to do in pre_build phase"
  build:
    commands:
      - echo "Copying index.html to S3 bucket"
#      - aws s3 cp index.html s3://your-s3-bucket-name/index.html
  post_build:
    commands:
    #  - echo "Restarting Apache2 service"
     # - sudo systemctl restart apache2
     # - echo "Deployment completed"
